# Generated by Django 5.2.6 on 2025-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(help_text='Car name', max_length=255)),
                ('car_model', models.CharField(help_text='Car Model', max_length=100)),
                ('mileage', models.IntegerField(help_text='FC Date')),
                ('car_ins_date', models.DateField(help_text='Insurance Date', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Car Rating (e.g., 8.5)', max_digits=3)),
            ],
        ),
    ]
